version: '{branch}-{build}'
build: off
cache:
  - '%LOCALAPPDATA%\pip\Cache'
environment:
  global:
    WITH_COMPILER: 'cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd'
  matrix:
    - NOXSESSION: check,mypy
      PYTHON_HOME: C:\Python38
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '32'
    - NOXSESSION: 'cover-3.8,codecov,report'
      PYTHON_HOME: C:\Python38
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '32'
    - NOXSESSION: 'cover-3.8,codecov,report'
      WINDOWS_SDK_VERSION: v7.1
      PYTHON_HOME: C:\Python38-x64
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '64'

    - NOXSESSION: 'nocov-3.8'
      PYTHON_HOME: C:\Python38
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '32'
    - NOXSESSION: 'nocov-3.8'
      WINDOWS_SDK_VERSION: v7.1
      PYTHON_HOME: C:\Python38-x64
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '64'

init:
  - ps: echo $env:NOXSESSION
  - ps: ls C:\Python*
install:
  - python -u ci\appveyor-bootstrap.py
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\easy_install --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\nox --version'
test_script:
  - '%WITH_COMPILER% %PYTHON_HOME%\Scripts\nox'

artifacts:
  - path: dist\*

### To enable remote debugging uncomment this (also, see: http://www.appveyor.com/docs/how-to/rdp-to-build-worker):
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
