language: python
sudo: true
cache: pip
python: '3.7'
dist: xenial
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
  matrix:
    - NOXSESSION=check,mypy
    - NOXSESSION=docs
matrix:
  include:
{%- for env, config in nox_environments|dictsort %}{{ '' }}
    - python: '{{ '{0[0]}-5.4'.format(env.split('-')) if env.startswith('pypy') else env.split('-')[0] }}'
      env:
        - NOXSESSION={{ env }}{% if config.cover %},codecov,report{% endif -%}
{% endfor %}

before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install nox
  - virtualenv --version
  - easy_install --version
  - pip --version
  - nox --version
script:
  - nox -v
notifications:
  email:
    on_success: never
    on_failure: always
